# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bricks < Formula
  desc ""
  homepage "https://github.com/bricks-cloud/homebrew-bricks"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bricks-cloud/bricks/releases/download/v0.0.3/bricks_0.0.3_Darwin-x86_64.tar.gz"
      sha256 "b12e7ea27e4b01d4222bdc0dcbf50f5b611dcb7e44da8d3ccdee84d4d30d9128"

      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bricks-cloud/bricks/releases/download/v0.0.3/bricks_0.0.3_Darwin-arm64.tar.gz"
      sha256 "4361e984348d4f7ce4cdfbe9d1d238a91832c863ad39481bc8c90f189daff581"

      def install
        bin.install "bricks"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bricks-cloud/bricks/releases/download/v0.0.3/bricks_0.0.3_Linux-arm64.tar.gz"
      sha256 "0f6ec9dff1da5c46fe0c86f12d86989e21a39e4e9e36d8f43f203d98e29bea24"

      def install
        bin.install "bricks"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bricks-cloud/bricks/releases/download/v0.0.3/bricks_0.0.3_Linux-x86_64.tar.gz"
      sha256 "7f42dbd18e9ea3947e31d7d0cc3530823ded66153d602fb9536196f05ff8e3d1"

      def install
        bin.install "bricks"
      end
    end
  end
end
